Fix build errors
- Fixes the following build errors:
  - src/components/JobCard.tsx(9,18): error TS2724: '"lucide-react"' has no exported member named 'BriefCase'. Did you mean 'Briefcase'?
  - src/components/StatisticsPanel.tsx(47,17): error TS2339: Property 'Chart' does not exist on type 'Window & typeof globalThis'.
  - src/components/StatisticsPanel.tsx(98,17): error TS2339: Property 'Chart' does not exist on type 'Window & typeof globalThis'.
  - src/components/StatisticsPanel.tsx(146,17): error TS2339: Property 'Chart' does not exist on type 'Window & typeof globalThis'.